global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: services_http
    metrics_path: /probe
    params:
      module: [http_2xx]

    static_configs:
      - targets:
          - http://markdown:3000/health
        labels:
          service: markdown

      - targets:
          - http://xray:8000/health
        labels:
          service: music

      - targets:
          - http://grafana:3000/api/health
        labels:
          service: grafana

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target

      - source_labels: [__param_target]
        target_label: instance

      - target_label: __address__
        replacement: blackbox:9115
